[Desktop Entry]
Encoding=UTF-8
Type=Service
Exec=blubb
Comment=Java Language Support
Comment[bg]=Поддръжка на езика Java
Comment[bs]=Podrška za jezik Java
Comment[ca]=Implementació de llenguatge Java
Comment[ca@valencia]=Implementació de llenguatge Java
Comment[de]=Sprachunterstützung für Java
Comment[el]=Υποστήριξη γλώσσας Java
Comment[en_GB]=Java Language Support
Comment[es]=Implementación de lenguaje Java
Comment[fi]=Java-kielituki
Comment[fr]=Prise en charge du langage Java
Comment[ga]=Tacaíocht Java
Comment[gl]=Soporte de Java
Comment[hne]=जावा भाखा समर्थन
Comment[hu]=Java nyelvi támogatás
Comment[it]=Supporto per il linguaggio Java
Comment[ja]=Java 言語のサポート
Comment[nds]=Ünnerstütten för Java
Comment[nl]=Ondersteuning voor de Java-taal
Comment[pa]=ਜਾਵਾ ਲੈਗੂਇਜ਼ ਸਹਿਯੋਗ
Comment[pl]=Obsługa języka Java
Comment[pt]=Suporte para a Linguagem Java
Comment[pt_BR]=Suporte à linguagem Java
Comment[sk]=Podpora jazyka Java
Comment[sv]=Stöd för språket Java
Comment[tr]=Java Dil Desteği
Comment[uk]=Підтримка мови Java
Comment[x-test]=xxJava Language Supportxx
Name=Java Support
Name[bg]=Поддръжка на Java
Name[bs]=Podrška za jezik Java
Name[ca]=Implementació Java
Name[ca@valencia]=Implementació Java
Name[de]=Unterstützung für Java
Name[en_GB]=Java Support
Name[es]=Implementación de Java
Name[fi]=Java-tuki
Name[fr]=Prise en charge de Java
Name[ga]=Tacaíocht Java
Name[gl]=Soporte de Java
Name[hu]=Java támogatás
Name[it]=Supporto per Java
Name[ja]=Java サポート
Name[nds]=Java-Ünnerstütten
Name[nl]=Ondersteuning voor Java
Name[pa]=ਜਾਵਾ ਸਹਿਯੋਗ
Name[pl]=Obsługa Java
Name[pt]=Suporte para Java
Name[pt_BR]=Suporte a Java
Name[sk]=Podpora Javy
Name[sv]=Java-stöd
Name[tr]=Java Desteği
Name[uk]=Підтримка Java
Name[x-test]=xxJava Supportxx
GenericName=Java Support
GenericName[bg]=Поддръжка на Java
GenericName[bs]=Podrška za jezik Java
GenericName[ca]=Implementació Java
GenericName[ca@valencia]=Implementació Java
GenericName[de]=Unterstützung für Java
GenericName[el]=Υποστήριξη Java
GenericName[en_GB]=Java Support
GenericName[es]=Implementación Java
GenericName[fi]=Java-tuki
GenericName[fr]=Prise en charge de Java
GenericName[ga]=Tacaíocht Java
GenericName[gl]=Soporte de Java
GenericName[hne]=जावा समर्थन
GenericName[hu]=Java támogatás
GenericName[it]=Supporto per Java
GenericName[ja]=Java サポート
GenericName[nds]=Java-Ünnerstütten
GenericName[nl]=Ondersteuning voor Java
GenericName[pa]=ਜਾਵਾ ਸਹਿਯੋਗ
GenericName[pl]=Obsługa Java
GenericName[pt]=Suporte para Java
GenericName[pt_BR]=Suporte a Java
GenericName[sk]=Podpora Javy
GenericName[sv]=Java-stöd
GenericName[tr]=Java Desteği
GenericName[uk]=Підтримка Java
GenericName[x-test]=xxJava Supportxx
ServiceTypes=KDevelop/Plugin
Icon=application-x-java
X-KDE-Library=kdevjavalanguagesupport
X-KDevelop-Version=@KDEV_PLUGIN_VERSION@
X-KDevelop-Language=Java
X-KDevelop-Interfaces=ILanguageSupport
X-KDevelop-SupportedMimeTypes=text/x-java
X-KDE-PluginInfo-Name=kdevjavasupport
X-KDevelop-Mode=NoGUI
X-KDE-PluginInfo-Category=Language Support
